### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by Beasta** [PBSA/peerplays#13]
following the instructions but on this one
`import_key "your_witness_username" xxxx`
i get the following error:
```

unlocked >>> import_key "myUsername" 5somelongkey
import_key "myUsername" 5somelongkey
10 assert_exception: Assert Exception
rec && rec->name == account_name_or_id:
    {}
    th_a  wallet.cpp:742 get_account
```

i've checked and rechecked to make sure I'm using the second value in the array from the previous step. i'm also sure that i'm using the same username as the previous step. any ideas?

**Comment by roelandp** [comment]
so please leave your username? then we can check and reproduce the error. The error indicates you don't have the correct username as apparently the username doesn't exist on the blockchain. Also try for fun without "" to see if that helps.

**Comment by Beasta** [comment]
username is bomb5hit5
i just logged back in at `https://595-dev.pixelplex.by/` to make sure that its correct

i was curious about the testnet chain-id in the instructions. am I supposed to set that somewhere?

**Comment by roelandp** [comment]
Are you using testnet seednode and testnet installation release tag?

Not sure if it is still up but i recommend checking older versions of the readme for instructions. Maybe you should also enable-stale-production as param. 

There are 2 testnets with same chain id as well so u might need to reconnect a few times untill you connect to the correct one. 

Good luck!

**Comment by educatedwarrior** [comment]
@Beasta , did you ever find resolution.  I"m having the same issue.

**Comment by Beasta** [comment]
@educatedwarrior nope, gave up

**Comment by bobinson** [comment]
inactive for too long. Reopen an issue in  https://github.com/peerplays-network/peerplays/ if there are any issues.
