### ISSUE TITLE
Peerplays GUI wallet - source code not published?

### ISSUE THREAD

**Issue by altrader** [PBSA/peerplays#17]
Multiple crowdfund contributors looking to claim their PPY tokens have asked a number of times on the Telegram channel for a link to the source code of the GUI wallet.
It's understandable that providing one's private key from a redemption file, or a BitShares private key to an application whose source code has not been reviewed would be a valid cause for concern.
For that reason, some contributors have been holding off claiming their PPY tokens and have therefore been unable to vote for witnesses.

**Comment by roelandp** [comment]
+1
